drop table roleassignment;
drop table candidateattendee;
drop table teammember;
drop table candidate;
drop table individual;
drop table cursilloweekend;
drop table role;
drop table parish;
drop table address;